'use strict';

const fs = require('node:fs');
const path = require('node:path');

const { TOOL_NAME } = require('../context');
const { run } = require('../core/runtime');
const { shellQuote } = require('./launch');

const DEFAULT_AGENT_TERMINAL = 'kitty';
const SUPPORTED_AGENT_TERMINALS = new Set(['kitty', 'none']);

function normalizeAgentTerminal(value) {
  const terminal = String(value || DEFAULT_AGENT_TERMINAL).trim().toLowerCase();
  return terminal || DEFAULT_AGENT_TERMINAL;
}

function sanitizeFileSegment(value) {
  return String(value || 'agents')
    .replace(/[^a-zA-Z0-9._-]+/g, '__')
    .replace(/^_+|_+$/g, '')
    .slice(0, 120) || 'agents';
}

function terminalSessionDir(repoRoot) {
  return path.join(repoRoot, '.guardex', 'agents', 'terminals');
}

function terminalSessionFilePath(repoRoot, sessions, terminal = DEFAULT_AGENT_TERMINAL) {
  const firstSession = sessions[0] || {};
  const sessionId = sanitizeFileSegment(firstSession.id || firstSession.branch || 'agents');
  return path.join(terminalSessionDir(repoRoot), `${sessionId}-${sessions.length}.${terminal}-session`);
}

function sessionTitle(session, index) {
  const branch = String(session.branch || session.id || `agent-${index + 1}`);
  const leaf = branch.split('/').filter(Boolean).pop() || branch;
  return `${index + 1}: ${session.agent || 'agent'} ${leaf}`;
}

function buildKittySession(sessions) {
  const lines = ['# Generated by gx agents start.'];
  sessions.forEach((session, index) => {
    const title = sessionTitle(session, index);
    lines.push(
      '',
      `new_tab ${shellQuote(title)}`,
      `cd ${shellQuote(session.worktreePath)}`,
      `launch --title ${shellQuote(title)} sh -lc ${shellQuote(session.launchCommand)}`,
    );
  });
  return `${lines.join('\n')}\n`;
}

function writeKittySessionFile(repoRoot, sessions) {
  const filePath = terminalSessionFilePath(repoRoot, sessions, 'kitty');
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, buildKittySession(sessions), { encoding: 'utf8', mode: 0o600 });
  return filePath;
}

function recoveryLines(sessionFilePath, reason) {
  const detail = reason ? `: ${reason}` : '.';
  return [
    `[${TOOL_NAME}] Kitty terminal not launched${detail}`,
    `[${TOOL_NAME}] Kitty session file: ${sessionFilePath}`,
    `[${TOOL_NAME}] Recovery: kitty --detach --session ${shellQuote(sessionFilePath)}`,
    `[${TOOL_NAME}] Agent lanes are intact; run the recovery command when Kitty is available.`,
    '',
  ].join('\n');
}

function resultReason(result, fallback) {
  if (result?.error?.message) return result.error.message;
  if (typeof result?.status === 'number') return `${fallback} exited ${result.status}`;
  return fallback;
}

function launchAgentTerminal(repoRoot, sessions, options = {}) {
  const terminal = normalizeAgentTerminal(options.terminal);
  if (terminal === 'none' || !Array.isArray(sessions) || sessions.length === 0) {
    return { status: 'skipped', stdout: '', stderr: '', sessionFilePath: '' };
  }
  if (!SUPPORTED_AGENT_TERMINALS.has(terminal)) {
    return {
      status: 'unsupported',
      stdout: '',
      stderr: `[${TOOL_NAME}] Unsupported agent terminal '${terminal}'. Supported terminals: kitty, none.\n`,
      sessionFilePath: '',
    };
  }

  const sessionFilePath = writeKittySessionFile(repoRoot, sessions);
  const runner = options.runner || run;
  if (typeof runner !== 'function') {
    return {
      status: 'missing',
      stdout: '',
      stderr: recoveryLines(sessionFilePath, 'terminal runner unavailable'),
      sessionFilePath,
    };
  }
  const kittyBin = options.kittyBin || process.env.GUARDEX_KITTY_BIN || 'kitty';
  const probe = runner(kittyBin, ['--version'], { cwd: repoRoot, stdio: 'pipe' });
  if (probe?.error || probe?.status !== 0) {
    return {
      status: 'missing',
      stdout: '',
      stderr: recoveryLines(sessionFilePath, resultReason(probe, `${kittyBin} --version`)),
      sessionFilePath,
    };
  }

  const launch = runner(kittyBin, ['--detach', '--session', sessionFilePath], { cwd: repoRoot, stdio: 'ignore' });
  if (launch?.error || launch?.status !== 0) {
    return {
      status: 'failed',
      stdout: '',
      stderr: recoveryLines(sessionFilePath, resultReason(launch, `${kittyBin} --detach`)),
      sessionFilePath,
    };
  }

  return {
    status: 'launched',
    stdout: `[${TOOL_NAME}] Kitty agent terminal: ${sessionFilePath}\n`,
    stderr: '',
    sessionFilePath,
  };
}

module.exports = {
  DEFAULT_AGENT_TERMINAL,
  buildKittySession,
  launchAgentTerminal,
  normalizeAgentTerminal,
  recoveryLines,
  terminalSessionFilePath,
  writeKittySessionFile,
};
